from future import utils as utils
from typing import Any

FS_ERRORS: str

def u(text: Any): ...
def b(data: Any): ...

bytes_chr: Any

def surrogateescape_handler(exc: Any): ...

class NotASurrogateError(Exception): ...

def replace_surrogate_encode(mystring: Any): ...
def replace_surrogate_decode(mybytes: Any): ...
def encodefilename(fn: Any): ...
def decodefilename(fn: Any): ...

FS_ENCODING: str
fn: Any
encoded: Any

def register_surrogateescape() -> None: ...
