doc-warnings: yes
test-warnings: no
strictness: high
max-line-length: 110
autodetect: yes
ignore-paths:
    # Ignore code that's not in the delivered
    - doc
    - tests
    - samples
    # Ignore build files
    - coverage_fix.py
    - version.py
python-targets:
    - 2
    - 3
pylint:
  disable:
    # Py2/3 compatibility
    - redefined-builtin
    # Need many attributes on widgets
    - too-many-arguments
    - too-many-locals
    - too-many-instance-attributes
    - invalid-name
    # Need conditional imports for Windows/Linux
    - wrong-import-order
    - import-error
    # Use pep257 to handle docstring issues
    - missing-docstring
    # Complexity isn't as bad as the metrics think - but stuff for v2.0
    - too-many-lines
    - too-many-branches
    - too-many-statements
    # Don't agree with these styles
    - no-else-return
    - len-as-condition
mccabe:
  run: false
pep257:
  disable:
    - D102
    - D200
    - D203
    - D205
    - D212
    - D400
    - D401
    - D404
