from future.builtins import dict
from typing import Any, Optional

class CookieError(Exception): ...

class Morsel(dict):
    key: Any = ...
    def __init__(self) -> None: ...
    def __setitem__(self, K: Any, V: Any) -> None: ...
    def isReservedKey(self, K: Any): ...
    value: Any = ...
    coded_value: Any = ...
    def set(self, key: Any, val: Any, coded_val: Any, LegalChars: Any = ...) -> None: ...
    def output(self, attrs: Optional[Any] = ..., header: str = ...): ...
    def js_output(self, attrs: Optional[Any] = ...): ...
    def OutputString(self, attrs: Optional[Any] = ...): ...

class BaseCookie(dict):
    def value_decode(self, val: Any): ...
    def value_encode(self, val: Any): ...
    def __init__(self, input: Optional[Any] = ...) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def output(self, attrs: Optional[Any] = ..., header: str = ..., sep: str = ...): ...
    def js_output(self, attrs: Optional[Any] = ...): ...
    def load(self, rawdata: Any) -> None: ...

class SimpleCookie(BaseCookie):
    def value_decode(self, val: Any): ...
    def value_encode(self, val: Any): ...
