from typing import Any

class BaseNewDict(type):
    def __instancecheck__(cls, instance: Any): ...

class newdict(_builtin_dict, metaclass=BaseNewDict):
    def items(self): ...
    def keys(self): ...
    def values(self): ...
    def __new__(cls, *args: Any, **kwargs: Any): ...
    def __native__(self): ...
