from collections.abc import Iterator, Sequence
from typing import Any

class newrange(Sequence):
    def __init__(self, *args: Any) -> None: ...
    @property
    def start(self): ...
    @property
    def stop(self): ...
    @property
    def step(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __len__(self): ...
    def index(self, value: Any): ...
    def count(self, value: Any): ...
    def __contains__(self, value: Any): ...
    def __reversed__(self): ...
    def __getitem__(self, index: Any): ...
    def __iter__(self) -> Any: ...

class range_iterator(Iterator):
    def __init__(self, range_: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self): ...
    def next(self): ...
