from typing import Any, Optional

unicode = str

class BaseNewStr(type):
    def __instancecheck__(cls, instance: Any): ...

class newstr(unicode, metaclass=BaseNewStr):
    no_convert_msg: str = ...
    def __new__(cls, *args: Any, **kwargs: Any): ...
    def __getitem__(self, y: Any): ...
    def __contains__(self, key: Any): ...
    def __add__(self, other: Any): ...
    def __radd__(self, left: Any): ...
    def __mul__(self, other: Any): ...
    def __rmul__(self, other: Any): ...
    def join(self, iterable: Any): ...
    def find(self, sub: Any, *args: Any): ...
    def rfind(self, sub: Any, *args: Any): ...
    def replace(self, old: Any, new: Any, *args: Any): ...
    def decode(self, *args: Any) -> None: ...
    def encode(self, encoding: str = ..., errors: str = ...): ...
    def startswith(self, prefix: Any, *args: Any): ...
    def endswith(self, prefix: Any, *args: Any): ...
    def split(self, sep: Optional[Any] = ..., maxsplit: int = ...): ...
    def rsplit(self, sep: Optional[Any] = ..., maxsplit: int = ...): ...
    def partition(self, sep: Any): ...
    def rpartition(self, sep: Any): ...
    def index(self, sub: Any, *args: Any): ...
    def splitlines(self, keepends: bool = ...): ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    unorderable_err: str = ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def __getattribute__(self, name: Any): ...
    def __native__(self): ...
    @staticmethod
    def maketrans(x: Any, y: Optional[Any] = ..., z: Optional[Any] = ...): ...
    def translate(self, table: Any): ...
    def isprintable(self) -> None: ...
    def isidentifier(self) -> None: ...
    def format_map(self) -> None: ...
