from future.builtins import object as object
from typing import Any, Optional

class addbase:
    fp: Any = ...
    read: Any = ...
    readline: Any = ...
    readlines: Any = ...
    fileno: Any = ...
    def __init__(self, fp: Any) -> None: ...
    def __iter__(self) -> Any: ...
    __next__: Any = ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: Any, value: Any, traceback: Any) -> None: ...

class addclosehook(addbase):
    closehook: Any = ...
    hookargs: Any = ...
    def __init__(self, fp: Any, closehook: Any, *hookargs: Any) -> None: ...
    def close(self) -> None: ...

class addinfo(addbase):
    headers: Any = ...
    def __init__(self, fp: Any, headers: Any) -> None: ...
    def info(self): ...

class addinfourl(addbase):
    headers: Any = ...
    url: Any = ...
    code: Any = ...
    def __init__(self, fp: Any, headers: Any, url: Any, code: Optional[Any] = ...) -> None: ...
    def info(self): ...
    def getcode(self): ...
    def geturl(self): ...
