from typing import Any

class RobotFileParser:
    entries: Any = ...
    default_entry: Any = ...
    disallow_all: bool = ...
    allow_all: bool = ...
    last_checked: int = ...
    def __init__(self, url: str = ...) -> None: ...
    def mtime(self): ...
    def modified(self) -> None: ...
    url: Any = ...
    def set_url(self, url: Any) -> None: ...
    def read(self) -> None: ...
    def parse(self, lines: Any) -> None: ...
    def can_fetch(self, useragent: Any, url: Any): ...

class RuleLine:
    path: Any = ...
    allowance: Any = ...
    def __init__(self, path: Any, allowance: Any) -> None: ...
    def applies_to(self, filename: Any): ...

class Entry:
    useragents: Any = ...
    rulelines: Any = ...
    def __init__(self) -> None: ...
    def applies_to(self, useragent: Any): ...
    def allowance(self, filename: Any): ...
