from typing import Any, Optional

def decode_q(encoded: Any): ...

class _QByteMap(dict):
    safe: Any = ...
    def __missing__(self, key: Any): ...

def encode_q(bstring: Any): ...
def len_q(bstring: Any): ...
def decode_b(encoded: Any): ...
def encode_b(bstring: Any): ...
def len_b(bstring: Any): ...
def decode(ew: Any): ...
def encode(string: Any, charset: str = ..., encoding: Optional[Any] = ..., lang: str = ...): ...
