from typing import Any, Optional

def parsedate_tz(data: Any): ...
def parsedate(data: Any): ...
def mktime_tz(data: Any): ...
def quote(str: Any): ...

class AddrlistClass:
    specials: str = ...
    pos: int = ...
    LWS: str = ...
    CR: str = ...
    FWS: Any = ...
    atomends: Any = ...
    phraseends: Any = ...
    field: Any = ...
    commentlist: Any = ...
    def __init__(self, field: Any) -> None: ...
    def gotonext(self): ...
    def getaddrlist(self): ...
    def getaddress(self): ...
    def getrouteaddr(self): ...
    def getaddrspec(self): ...
    def getdomain(self): ...
    def getdelimited(self, beginchar: Any, endchars: Any, allowcomments: bool = ...): ...
    def getquote(self): ...
    def getcomment(self): ...
    def getdomainliteral(self): ...
    def getatom(self, atomends: Optional[Any] = ...): ...
    def getphraselist(self): ...

class AddressList(AddrlistClass):
    addresslist: Any = ...
    def __init__(self, field: Any) -> None: ...
    def __len__(self): ...
    def __add__(self, other: Any): ...
    def __iadd__(self, other: Any): ...
    def __sub__(self, other: Any): ...
    def __isub__(self, other: Any): ...
    def __getitem__(self, index: Any): ...
