from typing import Any

def header_length(bytearray: Any): ...
def header_encode(header_bytes: Any, charset: str = ...): ...
def body_encode(s: Any, maxlinelen: int = ..., eol: Any = ...): ...
def decode(string: Any): ...
body_decode = decode
decodestring = decode
