from typing import Any, Optional

def add_charset(charset: Any, header_enc: Optional[Any] = ..., body_enc: Optional[Any] = ..., output_charset: Optional[Any] = ...) -> None: ...
def add_alias(alias: Any, canonical: Any) -> None: ...
def add_codec(charset: Any, codecname: Any) -> None: ...

class Charset:
    input_charset: Any = ...
    header_encoding: Any = ...
    body_encoding: Any = ...
    output_charset: Any = ...
    input_codec: Any = ...
    output_codec: Any = ...
    def __init__(self, input_charset: Any = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def get_body_encoding(self): ...
    def get_output_charset(self): ...
    def header_encode(self, string: Any): ...
    def header_encode_lines(self, string: Any, maxlengths: Any): ...
    def body_encode(self, string: Any): ...
