from typing import Any

class BufferedSubFile:
    def __init__(self) -> None: ...
    def push_eof_matcher(self, pred: Any) -> None: ...
    def pop_eof_matcher(self): ...
    def close(self) -> None: ...
    def readline(self): ...
    def unreadline(self, line: Any) -> None: ...
    def push(self, data: Any) -> None: ...
    def pushlines(self, lines: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self): ...

class FeedParser:
    policy: Any = ...
    def __init__(self, _factory: Any = ..., **_3to2kwargs: Any): ...
    def feed(self, data: Any) -> None: ...
    def close(self): ...

class BytesFeedParser(FeedParser):
    def feed(self, data: Any) -> None: ...
