from typing import Any, Optional

def walk(self) -> None: ...
def body_line_iterator(msg: Any, decode: bool = ...) -> None: ...
def typed_subpart_iterator(msg: Any, maintype: str = ..., subtype: Optional[Any] = ...) -> None: ...
