from typing import Any

class Parser:
    policy: Any = ...
    def __init__(self, _class: Any = ..., **_3to2kwargs: Any) -> None: ...
    def parse(self, fp: Any, headersonly: bool = ...): ...
    def parsestr(self, text: Any, headersonly: bool = ...): ...

class HeaderParser(Parser):
    def parse(self, fp: Any, headersonly: bool = ...): ...
    def parsestr(self, text: Any, headersonly: bool = ...): ...

class BytesParser:
    parser: Any = ...
    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def parse(self, fp: Any, headersonly: bool = ...): ...
    def parsebytes(self, text: Any, headersonly: bool = ...): ...

class BytesHeaderParser(BytesParser):
    def parse(self, fp: Any, headersonly: bool = ...): ...
    def parsebytes(self, text: Any, headersonly: bool = ...): ...
