from future.standard_library.email._policybase import Compat32 as Compat32, Policy as Policy, compat32 as compat32
from typing import Any

class EmailPolicy(Policy):
    refold_source: str = ...
    header_factory: Any = ...
    def __init__(self, **kw: Any) -> None: ...
    def header_max_count(self, name: Any): ...
    def header_source_parse(self, sourcelines: Any): ...
    def header_store_parse(self, name: Any, value: Any): ...
    def header_fetch_parse(self, name: Any, value: Any): ...
    def fold(self, name: Any, value: Any): ...
    def fold_binary(self, name: Any, value: Any): ...

default: Any
strict: Any
SMTP: Any
HTTP: Any
