import io
from typing import Any

def header_length(bytearray: Any): ...
def body_length(bytearray: Any): ...
def unquote(s: Any): ...
def quote(c: Any): ...
def header_encode(header_bytes: Any, charset: str = ...): ...

class _body_accumulator(io.StringIO):
    eol: Any = ...
    maxlinelen: Any = ...
    def __init__(self, maxlinelen: Any, eol: Any, *args: Any, **kw: Any) -> None: ...
    def write_str(self, s: Any) -> None: ...
    room: Any = ...
    def newline(self) -> None: ...
    def write_soft_break(self) -> None: ...
    def write_wrapped(self, s: Any, extra_room: int = ...) -> None: ...
    def write_char(self, c: Any, is_last_char: Any) -> None: ...

def body_encode(body: Any, maxlinelen: int = ..., eol: Any = ...): ...
def decode(encoded: Any, eol: Any = ...): ...
body_decode = decode
decodestring = decode

def header_decode(s: Any): ...
