from future.backports.email._parseaddr import mktime_tz as mktime_tz, parsedate as parsedate, parsedate_tz as parsedate_tz
from typing import Any, Optional

def formataddr(pair: Any, charset: str = ...): ...
def getaddresses(fieldvalues: Any): ...
def formatdate(timeval: Optional[Any] = ..., localtime: bool = ..., usegmt: bool = ...): ...
def format_datetime(dt: Any, usegmt: bool = ...): ...
def make_msgid(idstring: Optional[Any] = ..., domain: Optional[Any] = ...): ...
def parsedate_to_datetime(data: Any): ...
def parseaddr(addr: Any): ...
def unquote(str: Any): ...
def decode_rfc2231(s: Any): ...
def encode_rfc2231(s: Any, charset: Optional[Any] = ..., language: Optional[Any] = ...): ...
def decode_params(params: Any): ...
def collapse_rfc2231_value(value: Any, errors: str = ..., fallback_charset: str = ...): ...
