from future import utils as utils
from typing import Any

def newmin(*args: Any, **kwargs: Any): ...
def newmax(*args: Any, **kwargs: Any): ...
def new_min_max(_builtin_func: Any, *args: Any, **kwargs: Any): ...
