from typing import Any

class ParserBase:
    def __init__(self) -> None: ...
    def error(self, message: Any) -> None: ...
    lineno: int = ...
    offset: int = ...
    def reset(self) -> None: ...
    def getpos(self): ...
    def updatepos(self, i: Any, j: Any): ...
    def parse_declaration(self, i: Any): ...
    def parse_marked_section(self, i: Any, report: int = ...): ...
    def parse_comment(self, i: Any, report: int = ...): ...
    def unknown_decl(self, data: Any) -> None: ...
